### Q_1: create 2D-array that contain even numbers between 0-18...??

In [1]:
import numpy as np
an_2=np.array([[2,4,6,8],[10,12,14,18]])
print(an_2.ndim)

2


### Q_2: Replace the negative values with 0 in random array that has value in range (-6,6)

In [2]:
arr_negative=np.array([-6,-5,-4,-3,-2,-1,0,1,2,3,4,5,6])
print("Before ",arr_negative)
i=0
while (arr_negative[i]<0) :
    arr_negative[i]=0
    i=i+1
print("After ",arr_negative)

Before  [-6 -5 -4 -3 -2 -1  0  1  2  3  4  5  6]
After  [0 0 0 0 0 0 0 1 2 3 4 5 6]


### Q_3 :  How to compute ((A+B)*(-A/2)) ?  where A,B random array

In [14]:
arr1=np.random.rand(3)
arr2=np.random.rand(3)
print((arr1+arr2)*(-arr1/2))

[-0.31276766 -0.3215128  -0.31327089]


### Q_4: How to concatenate two arrays horizontally..?

In [15]:
arra=np.array([10,20,30])
arrb=np.array([40,50,60])
arr_concat=np.concatenate((arra,arrb),axis=0)
print(arr_concat)

[10 20 30 40 50 60]


#### Q_5: Create a array vector of size 3x3 and sort values in Its columns

In [16]:
arr_vector=np.array([[50,20,10],[60,80,40],[40,30,70]])
print("Before Sorting\n",arr_vector)
arr_sorted=np.sort(arr_vector,axis=0)
print("==========================")
print("After Sorting\n",arr_sorted)

Before Sorting
 [[50 20 10]
 [60 80 40]
 [40 30 70]]
After Sorting
 [[40 20 10]
 [50 30 40]
 [60 80 70]]
